server:
  port: 8080

spring:
  servlet:
    context-path: '/encryption'

  datasource:
    url: jdbc:h2:file:/home/tqi_rbernardes/Documents/Estudos/bd-files/encryption;DB_CLOSE_DELAY=-1;IFEXISTS=FALSE
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true