spring:
  port: 8082
  servlet:
    context-path: '/encryption'

  datasource:
    url: jdbc:h2:mem:encryption
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true